### ISSUE TITLE
failed login with http status code 403

### ISSUE THREAD

**Issue by sultanmaa0** [akasakaid/onchaincoin_bot#3]
![image](https://github.com/akasakaid/onchenbot/assets/136260941/f0b23fd3-56a8-46a1-99fa-ffb09fe9c165)
first time running is fine, but after that, it became like this

**Comment by akasakaid** [comment]
have you filled in the data file?

**Comment by sultanmaa0** [comment]
> have you filled in the data file?

![image](https://github.com/akasakaid/onchenbot/assets/136260941/7d280ae0-3ce7-4074-9fb4-7fdebea6b8a8)
i did it. it only work for first hour, after that error
